# SUSTRACTION
print(3-4)
# DIVISION
print(3/4)
# ADDITION
print(3+4)
# FLOOR DISIVION OPERATOR
print(3//4)
# MODULUS
print(3%4)
# EXPONENTIAL
print(3**4)
# MULTIPLICATION
print(3*4)

# EJERCICIO 3

#YOUR NAME
print("MY NAME IS EDUARDO")
# YOUR FAMILY NAME
print("MY MOTHERS NAMES KARINA")
# YOUR COUNTRY
print("MI COUNTRYS AGUASCALIENTES")
print("IM ENJOYING 30 DAYS OF PYTHON")
